version: '3.1'

services:
    php:
        image: server
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 5555:80
        volumes:
            - ./api:/var/www/html

    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
         - ./sql/db.sql:/docker-entrypoint-initdb.d/db.sql


    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1

volumes:
    sql:
